version: '3'

services:
  database_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - postgres-compose-network

  users_api:
    build:
      context: ./users-api
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./users-api/.env
    environment:
      - TYPEORM_HOST=database_postgres
    ports:
      - "3334:3334"
    links:
      - database_postgres
    container_name: users_api
    networks:
      - postgres-compose-network

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks: 
  postgres-compose-network:
    driver: bridge